pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'ca3e514b-32b9-4ac2-ab59-c733071649c5'
        DOCKERHUB_REPO = 'gregtish/inclass_tasks'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/GrigoriiTishchuk/inclass_tasks.git'
            }
        }



        stage('Create .env') {
                    steps {
                        withCredentials([usernamePassword(credentialsId: 'edujournal-db',
                                                          usernameVariable: 'DB_USER',
                                                          passwordVariable: 'DB_PASS')]) {
                            bat '''
                                echo DB_HOST=localhost > .env
                                echo DB_PORT=3306 >> .env
                                echo DB_NAME=temperature_converter >> .env
                                echo DB_USERNAME=%DB_USER% >> .env
                                echo DB_PASSWORD=%DB_PASS% >> .env
                                echo DB_URL=jdbc:mariadb://localhost:3306/temperature_converter >> .env

                                echo DB_HOST=host.docker.internal > .env.docker
                                echo DB_PORT=3306 >> .env.docker
                                echo DB_NAME=temperature_converter >> .env.docker
                                echo DB_USERNAME=%DB_USER% >> .env.docker
                                echo DB_PASSWORD=%DB_PASS% >> .env.docker
                                echo DB_URL=jdbc:mariadb://host.docker.internal:3306/temperature_converter >> .env.docker
                            '''
                        }
                    }
                }



        stage('Run Tests & Build') {
            steps {
                dir('task1') {
                    bat 'mvn clean verify'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'task1/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco execPattern: 'task1/target/jacoco.exec'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('task1') {
                    script {
                        bat "docker build -t ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG} ."
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }
    }
}